# Generated by Django 5.0.7 on 2024-08-06 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProductAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_type', models.CharField(choices=[('J', 'Job'), ('G', 'Gig'), ('R', 'Rental'), ('S', 'Sale'), ('SV', 'Service'), ('EV', 'Event'), ('C', 'Class')], default='S', help_text='Select the category for the post.', max_length=2)),
                ('title', models.CharField(help_text='Enter the title of the post.', max_length=255)),
                ('image', models.ImageField(blank=True, help_text='Upload an image for the post (optional).', null=True, upload_to='images/')),
                ('tags', models.CharField(blank=True, help_text='Enter comma-separated tags for the post (optional).', max_length=255)),
                ('location', models.CharField(help_text='Enter the location for the post.', max_length=255)),
                ('postal_code', models.CharField(help_text='Enter the postal code for the location.', max_length=20)),
                ('description', models.TextField(help_text='Enter the description of the post.')),
                ('price', models.PositiveIntegerField(help_text='Enter the price (must be a positive number).')),
                ('email', models.EmailField(help_text='Enter a valid email address for contact.', max_length=254)),
                ('show_email', models.BooleanField(default=True)),
                ('phone', models.CharField(blank=True, help_text='Enter a phone number for contact (optional).', max_length=15)),
                ('show_phone', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ad.category')),
            ],
        ),
    ]
