# Generated by Django 5.0.7 on 2024-08-07 08:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0002_remove_productad_category_jobad_delete_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('DA', 'Daily'), ('WE', 'Weekend'), ('WO', 'Workshop'), ('WO', 'Weekdays')], default='DA', max_length=2)),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/sale')),
                ('tags', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('show_email', models.BooleanField(default=True)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('show_phone', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('EL', 'Electronics'), ('FU', 'Furniture'), ('BE', 'Beauty'), ('JW', 'Jwellary'), ('GR', 'Grocery'), ('BK', 'Books'), ('FA', 'Fashion')], default='FA', max_length=2)),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/sale')),
                ('tags', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('show_email', models.BooleanField(default=True)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('show_phone', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RentalAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('FT', 'Flat'), ('PT', 'Furniture'), ('IN', 'Electronics'), ('VH', 'Vehicals')], default='FT', max_length=2)),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/rentals')),
                ('tags', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('charge', models.PositiveIntegerField()),
                ('period', models.CharField(choices=[('FT', 'Flat'), ('PT', 'Furniture'), ('IN', 'Electronics'), ('VH', 'Vehicals')], default='FT', max_length=3)),
                ('email', models.EmailField(max_length=254)),
                ('show_email', models.BooleanField(default=True)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('show_phone', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentalads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SaleAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('EL', 'Electronics'), ('FU', 'Furniture'), ('BE', 'Beauty'), ('JW', 'Jwellary'), ('GR', 'Grocery'), ('BK', 'Books'), ('FA', 'Fashion')], default='FA', max_length=2)),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/sale')),
                ('tags', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('show_email', models.BooleanField(default=True)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('show_phone', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saleads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('IN', 'Insurance'), ('CT', 'Contruction'), ('LE', 'Legal'), ('WM', 'Waste Management'), ('GR', 'Gadget Repairing')], default='IN', max_length=2)),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/sale')),
                ('tags', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('show_email', models.BooleanField(default=True)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('show_phone', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serviceads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
