# Generated by Django 5.0.7 on 2024-08-07 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0003_classad_eventad_rentalad_salead_servicead'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salead',
            name='location',
        ),
        migrations.RemoveField(
            model_name='salead',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='servicead',
            name='location',
        ),
        migrations.RemoveField(
            model_name='servicead',
            name='postal_code',
        ),
        migrations.AlterField(
            model_name='classad',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/classes'),
        ),
        migrations.AlterField(
            model_name='eventad',
            name='category',
            field=models.CharField(choices=[('FE', 'Festival'), ('SE', 'Seminar'), ('SP', 'Sports Event'), ('MO', 'Modeling')], default='FE', max_length=2),
        ),
        migrations.AlterField(
            model_name='eventad',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/events'),
        ),
        migrations.AlterField(
            model_name='rentalad',
            name='period',
            field=models.CharField(choices=[('FT', 'Flat'), ('PT', 'Furniture'), ('IN', 'Electronics'), ('VH', 'Vehicals')], default='D', max_length=2),
        ),
        migrations.AlterField(
            model_name='salead',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/sales'),
        ),
        migrations.AlterField(
            model_name='servicead',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/services'),
        ),
    ]
