# Generated by Django 5.0.7 on 2024-08-07 09:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0004_remove_salead_location_remove_salead_postal_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classad',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='classad',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
