# Generated by Django 5.0.7 on 2024-08-20 06:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0009_classmessage_eventmessage_jobmessage_rentalmessage_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventmessage',
            name='ad',
        ),
        migrations.RemoveField(
            model_name='eventmessage',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='eventmessage',
            name='user',
        ),
        migrations.RemoveField(
            model_name='jobmessage',
            name='ad',
        ),
        migrations.RemoveField(
            model_name='jobmessage',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='jobmessage',
            name='user',
        ),
        migrations.RemoveField(
            model_name='rentalmessage',
            name='ad',
        ),
        migrations.RemoveField(
            model_name='rentalmessage',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='rentalmessage',
            name='user',
        ),
        migrations.RemoveField(
            model_name='salemessage',
            name='ad',
        ),
        migrations.RemoveField(
            model_name='salemessage',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='salemessage',
            name='user',
        ),
        migrations.RemoveField(
            model_name='servicemessage',
            name='ad',
        ),
        migrations.RemoveField(
            model_name='servicemessage',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='servicemessage',
            name='user',
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='ad.message')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ClassMessage',
        ),
        migrations.DeleteModel(
            name='EventMessage',
        ),
        migrations.DeleteModel(
            name='JobMessage',
        ),
        migrations.DeleteModel(
            name='RentalMessage',
        ),
        migrations.DeleteModel(
            name='SaleMessage',
        ),
        migrations.DeleteModel(
            name='ServiceMessage',
        ),
    ]
