# Generated by Django 5.0.7 on 2024-08-22 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0011_alter_jobad_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobad',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/jobs'),
        ),
        migrations.CreateModel(
            name='AdImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('job_ad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ad.jobad')),
                ('rental_ad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ad.rentalad')),
            ],
        ),
    ]
