# Generated by Django 5.0.7 on 2024-08-22 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0012_alter_jobad_image_adimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='adimage',
            name='class_ad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ad.classad'),
        ),
        migrations.AddField(
            model_name='adimage',
            name='event_ad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ad.eventad'),
        ),
        migrations.AddField(
            model_name='adimage',
            name='sale_ad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ad.salead'),
        ),
        migrations.AddField(
            model_name='adimage',
            name='service_ad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ad.servicead'),
        ),
    ]
