# Generated by Django 5.0.7 on 2024-08-22 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0013_adimage_class_ad_adimage_event_ad_adimage_sale_ad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classad',
            name='image',
        ),
        migrations.RemoveField(
            model_name='eventad',
            name='image',
        ),
        migrations.RemoveField(
            model_name='jobad',
            name='image',
        ),
        migrations.RemoveField(
            model_name='rentalad',
            name='image',
        ),
        migrations.RemoveField(
            model_name='salead',
            name='image',
        ),
        migrations.RemoveField(
            model_name='servicead',
            name='image',
        ),
    ]
