# Generated by Django 5.0.7 on 2024-08-23 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0014_remove_classad_image_remove_eventad_image_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adimage',
            name='class_ad',
        ),
        migrations.RemoveField(
            model_name='adimage',
            name='event_ad',
        ),
        migrations.RemoveField(
            model_name='adimage',
            name='job_ad',
        ),
        migrations.RemoveField(
            model_name='adimage',
            name='rental_ad',
        ),
        migrations.RemoveField(
            model_name='adimage',
            name='sale_ad',
        ),
        migrations.RemoveField(
            model_name='adimage',
            name='service_ad',
        ),
        migrations.AddField(
            model_name='adimage',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='adimage',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
